on: pull_request

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        python:
          - 3.6
          - 3.7
          - 3.8
          - 3.9
          - 3.10-rc
    runs-on: ubuntu-latest
    container:
      image: python:${{ matrix.python }}
    steps:
      - uses: actions/checkout@v2
      - run: apt-get update
      - run: apt-get install -y -qq --no-install-recommends automake autoconf libtool autopoint gettext libglib2.0-dev python-gi-dev libbluetooth-dev libgirepository1.0-dev gir1.2-gtk-3.0 gir1.2-appindicator3-0.1 gir1.2-nm-1.0 libpulse0 libpulse-mainloop-glib0
      - run: automake --version
